<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="contacts" nsURI="http://www.example.org/contacts" nsPrefix="contacts">
  <eSubpackages name="base" nsURI="http://www.example.org/contacts/base" nsPrefix="base">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractObjetAuditable" abstract="true"
        eSuperTypes="#//base/AbstractObjet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="creePar" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateCreation" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifiePar" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateModification" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractObjetReference" abstract="true"
        eSuperTypes="#//base/AbstractObjetAuditable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="actif" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractNomenclature" abstract="true"
        eSuperTypes="#//base/AbstractObjetReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractObjet" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
          changeable="false" iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractEntite" abstract="true" eSuperTypes="#//base/AbstractObjetReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="adresse" upperBound="-1"
          eType="#//localisation/Adresse" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="moyendecommunication"
          upperBound="-1" eType="#//communication/MoyenDeCommunication" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="nomenclature" nsURI="http://www.example.org/contacts/nomenclature"
      nsPrefix="nomenclature">
    <eClassifiers xsi:type="ecore:EClass" name="Civilite" eSuperTypes="#//base/AbstractNomenclature"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeMoyenDeCommunication" eSuperTypes="#//base/AbstractNomenclature"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeNote" eSuperTypes="#//base/AbstractNomenclature"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeAction" eSuperTypes="#//base/AbstractNomenclature"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeAdresse" eSuperTypes="#//base/AbstractNomenclature"/>
    <eClassifiers xsi:type="ecore:EClass" name="Fonction" eSuperTypes="#//base/AbstractNomenclature"/>
    <eClassifiers xsi:type="ecore:EClass" name="StatusJuridique" eSuperTypes="#//base/AbstractNomenclature"/>
    <eClassifiers xsi:type="ecore:EClass" name="GroupeContact" eSuperTypes="#//base/AbstractNomenclature"/>
    <eClassifiers xsi:type="ecore:EClass" name="TypeDocument" eSuperTypes="#//base/AbstractNomenclature"/>
  </eSubpackages>
  <eSubpackages name="localisation" nsURI="http://www.example.org/contacts/localisation"
      nsPrefix="localisation">
    <eClassifiers xsi:type="ecore:EClass" name="CoordonneeGeographique" eSuperTypes="#//base/AbstractObjet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lattitude" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pays" eSuperTypes="#//base/AbstractObjetReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeINSEE" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeISO" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeAlpha2" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeAlpha3" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="indicatifTel" ordered="false"
          unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Commune" eSuperTypes="#//base/AbstractObjetReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeINSEE" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="slug" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" unique="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nomSimple" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nomReel" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="soudex" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaphone" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="codesPostaux" unique="false"
          lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Adresse" eSuperTypes="#//base/AbstractObjetAuditable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ligne1" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ligne2" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ligne3" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pays" lowerBound="1"
          eType="#//localisation/Pays"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="commune" eType="#//localisation/Commune"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="codePostal" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="communeHorsFrance" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="coordonnees" upperBound="-1"
          eType="#//localisation/CoordonneeGeographique" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//nomenclature/TypeAdresse"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="contacts" nsURI="http://www.example.org/contacts/contacts" nsPrefix="contacts">
    <eClassifiers xsi:type="ecore:EClass" name="contact" eSuperTypes="#//base/AbstractEntite">
      <eStructuralFeatures xsi:type="ecore:EReference" name="civilite" lowerBound="1"
          eType="#//nomenclature/Civilite"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" unique="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prenom" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="note" upperBound="-1"
          eType="#//actions/Note" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="compterendu" upperBound="-1"
          eType="#//actions/Action" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="groupes" lowerBound="1"
          upperBound="-1" eType="#//nomenclature/GroupeContact"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="employes" upperBound="-1"
          eType="#//contacts/Rattachement" eOpposite="#//contacts/Rattachement/contact"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Organisation" eSuperTypes="#//base/AbstractEntite">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="raisonSociale" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="siren" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="siret" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ape" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statusjuridique" eType="#//nomenclature/StatusJuridique"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="employes" upperBound="-1"
          eType="#//contacts/Rattachement" eOpposite="#//contacts/Rattachement/organisation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rattachement" eSuperTypes="#//base/AbstractObjetAuditable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="organisation" eType="#//contacts/Organisation"
          eOpposite="#//contacts/Organisation/employes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contact" eType="#//contacts/contact"
          eOpposite="#//contacts/contact/employes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fonction" lowerBound="1"
          eType="#//nomenclature/Fonction"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="communication" nsURI="http://www.example.org/contacts/communication"
      nsPrefix="communications">
    <eClassifiers xsi:type="ecore:EClass" name="MoyenDeCommunication" eSuperTypes="#//base/AbstractObjet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="valeur" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentaires" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//nomenclature/TypeMoyenDeCommunication"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="actions" nsURI="http://www.example.org/contacts/actions" nsPrefix="actions">
    <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="#//base/AbstractObjetReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Contenu" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//nomenclature/TypeNote"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="privee" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//base/AbstractObjetReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//nomenclature/TypeAction"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateAction" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="compteRenduPrive" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectifs" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="compteRendu" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="conclusions" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="piecesJointes" upperBound="-1"
          eType="#//actions/PieceJointe" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="realiseePar" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PieceJointe" eSuperTypes="#//base/AbstractObjetAuditable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//nomenclature/TypeDocument"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="auteurVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriDocument" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="securite" nsURI="http://www.example.org/contacts/securite" nsPrefix="securite">
    <eClassifiers xsi:type="ecore:EClass" name="Droit" eSuperTypes="#//base/AbstractObjetAuditable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="autorisation" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Profil" eSuperTypes="#//base/AbstractObjetAuditable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="droit" upperBound="-1"
          eType="#//securite/Droit" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Utilisateur" eSuperTypes="#//base/AbstractObjetAuditable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prenom" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="login" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="motDePasse" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="profiles" lowerBound="1"
          upperBound="-1" eType="#//securite/Profil"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
